print("Hello World")
Name= input("What is your name? ") #default is string
Age = int(input("How old are you? "))
print(type(Name)) #type
print(type(Age))
print("My name is", Name, "and I am", Age, "years old.")
print("My name is"+ Name +"and I am",Age ,"years old.") #cant concatenate string and int
print(f"My name is {Name} and I am {Age} years old.")
print(Name,Age) #comma means a space
print("Thank you..")

#+meansnospace #,meansspace